
// This file has been generated by the GUI designer. Do not modify.
namespace LiqPayDemo
{
	public partial class ViewBalanceWidget
	{
		private global::Gtk.VBox contentVBox;
		private global::Gtk.Table table3;
		private global::Gtk.Entry merchantIdEntry;
		private global::Gtk.Label merchantIdLabel;
		private global::Gtk.Entry pwdEntry;
		private global::Gtk.Label pwdLabel;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView balanceTextView;
		private global::Gtk.HButtonBox viewBalanceButtonBox;
		private global::Gtk.Button refreshBalanceButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LiqPayDemo.ViewBalanceWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LiqPayDemo.ViewBalanceWidget";
			// Container child LiqPayDemo.ViewBalanceWidget.Gtk.Container+ContainerChild
			this.contentVBox = new global::Gtk.VBox ();
			this.contentVBox.Name = "contentVBox";
			this.contentVBox.Spacing = 6;
			// Container child contentVBox.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.merchantIdEntry = new global::Gtk.Entry ();
			this.merchantIdEntry.CanFocus = true;
			this.merchantIdEntry.Name = "merchantIdEntry";
			this.merchantIdEntry.IsEditable = true;
			this.merchantIdEntry.InvisibleChar = '●';
			this.table3.Add (this.merchantIdEntry);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table3 [this.merchantIdEntry]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.merchantIdLabel = new global::Gtk.Label ();
			this.merchantIdLabel.Name = "merchantIdLabel";
			this.merchantIdLabel.Xalign = 1F;
			this.merchantIdLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Merchant ID:");
			this.merchantIdLabel.Justify = ((global::Gtk.Justification)(1));
			this.table3.Add (this.merchantIdLabel);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.merchantIdLabel]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.pwdEntry = new global::Gtk.Entry ();
			this.pwdEntry.CanFocus = true;
			this.pwdEntry.Name = "pwdEntry";
			this.pwdEntry.IsEditable = true;
			this.pwdEntry.InvisibleChar = '●';
			this.table3.Add (this.pwdEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.pwdEntry]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.pwdLabel = new global::Gtk.Label ();
			this.pwdLabel.Name = "pwdLabel";
			this.pwdLabel.Xalign = 1F;
			this.pwdLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
			this.pwdLabel.Justify = ((global::Gtk.Justification)(1));
			this.table3.Add (this.pwdLabel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.pwdLabel]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.contentVBox.Add (this.table3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.contentVBox [this.table3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child contentVBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.balanceTextView = new global::Gtk.TextView ();
			this.balanceTextView.CanFocus = true;
			this.balanceTextView.Name = "balanceTextView";
			this.balanceTextView.Editable = false;
			this.GtkScrolledWindow1.Add (this.balanceTextView);
			this.contentVBox.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.contentVBox [this.GtkScrolledWindow1]));
			w7.Position = 1;
			// Container child contentVBox.Gtk.Box+BoxChild
			this.viewBalanceButtonBox = new global::Gtk.HButtonBox ();
			this.viewBalanceButtonBox.Name = "viewBalanceButtonBox";
			this.viewBalanceButtonBox.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child viewBalanceButtonBox.Gtk.ButtonBox+ButtonBoxChild
			this.refreshBalanceButton = new global::Gtk.Button ();
			this.refreshBalanceButton.CanFocus = true;
			this.refreshBalanceButton.Name = "refreshBalanceButton";
			this.refreshBalanceButton.UseUnderline = true;
			this.refreshBalanceButton.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
			this.viewBalanceButtonBox.Add (this.refreshBalanceButton);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.viewBalanceButtonBox [this.refreshBalanceButton]));
			w8.Expand = false;
			w8.Fill = false;
			this.contentVBox.Add (this.viewBalanceButtonBox);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.contentVBox [this.viewBalanceButtonBox]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.contentVBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.refreshBalanceButton.Clicked += new global::System.EventHandler (this.OnViewBalanceClicked);
		}
	}
}
