
// This file has been generated by the GUI designer. Do not modify.
namespace LiqPayDemo
{
	public partial class MainWindow
	{
		private global::Gtk.Notebook actionsNotebook;

		private global::LiqPayDemo.ViewExchangeRatesWidget viewExchangeRatesWidget;

		private global::Gtk.Label exchangeActionLabel;

		private global::LiqPayDemo.ViewBalanceWidget viewBalanceWidget;

		private global::Gtk.Label viewBalanceLabel;

		private global::LiqPayDemo.SendMoneyWidget sendMoneyWidget;

		private global::Gtk.Label sendMoneyPageLabel;

		private global::LiqPayDemo.ViewTransactionWidget viewTransactionWidget;

		private global::Gtk.Label viewTransactionPageLabel;

		private global::LiqPayDemo.PhoneCreditWidget phoneCreditWidget;

		private global::Gtk.Label phoneCreditLabel;

		private global::LiqPayDemo.ClickNBuyWidget clicknbuyWidget;

		private global::Gtk.Label clicknbuyLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LiqPayDemo.MainWindow
			this.Name = "LiqPayDemo.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child LiqPayDemo.MainWindow.Gtk.Container+ContainerChild
			this.actionsNotebook = new global::Gtk.Notebook ();
			this.actionsNotebook.CanFocus = true;
			this.actionsNotebook.Name = "actionsNotebook";
			this.actionsNotebook.CurrentPage = 4;
			// Container child actionsNotebook.Gtk.Notebook+NotebookChild
			this.viewExchangeRatesWidget = new global::LiqPayDemo.ViewExchangeRatesWidget ();
			this.viewExchangeRatesWidget.Events = ((global::Gdk.EventMask)(256));
			this.viewExchangeRatesWidget.Name = "viewExchangeRatesWidget";
			this.actionsNotebook.Add (this.viewExchangeRatesWidget);
			// Notebook tab
			this.exchangeActionLabel = new global::Gtk.Label ();
			this.exchangeActionLabel.Name = "exchangeActionLabel";
			this.exchangeActionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Exchange");
			this.actionsNotebook.SetTabLabel (this.viewExchangeRatesWidget, this.exchangeActionLabel);
			this.exchangeActionLabel.ShowAll ();
			// Container child actionsNotebook.Gtk.Notebook+NotebookChild
			this.viewBalanceWidget = new global::LiqPayDemo.ViewBalanceWidget ();
			this.viewBalanceWidget.Events = ((global::Gdk.EventMask)(256));
			this.viewBalanceWidget.Name = "viewBalanceWidget";
			this.actionsNotebook.Add (this.viewBalanceWidget);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.actionsNotebook[this.viewBalanceWidget]));
			w2.Position = 1;
			// Notebook tab
			this.viewBalanceLabel = new global::Gtk.Label ();
			this.viewBalanceLabel.Name = "viewBalanceLabel";
			this.viewBalanceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("View Balance");
			this.actionsNotebook.SetTabLabel (this.viewBalanceWidget, this.viewBalanceLabel);
			this.viewBalanceLabel.ShowAll ();
			// Container child actionsNotebook.Gtk.Notebook+NotebookChild
			this.sendMoneyWidget = new global::LiqPayDemo.SendMoneyWidget ();
			this.sendMoneyWidget.Events = ((global::Gdk.EventMask)(256));
			this.sendMoneyWidget.Name = "sendMoneyWidget";
			this.actionsNotebook.Add (this.sendMoneyWidget);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.actionsNotebook[this.sendMoneyWidget]));
			w3.Position = 2;
			// Notebook tab
			this.sendMoneyPageLabel = new global::Gtk.Label ();
			this.sendMoneyPageLabel.Name = "sendMoneyPageLabel";
			this.sendMoneyPageLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Send Money");
			this.actionsNotebook.SetTabLabel (this.sendMoneyWidget, this.sendMoneyPageLabel);
			this.sendMoneyPageLabel.ShowAll ();
			// Container child actionsNotebook.Gtk.Notebook+NotebookChild
			this.viewTransactionWidget = new global::LiqPayDemo.ViewTransactionWidget ();
			this.viewTransactionWidget.Events = ((global::Gdk.EventMask)(256));
			this.viewTransactionWidget.Name = "viewTransactionWidget";
			this.actionsNotebook.Add (this.viewTransactionWidget);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.actionsNotebook[this.viewTransactionWidget]));
			w4.Position = 3;
			// Notebook tab
			this.viewTransactionPageLabel = new global::Gtk.Label ();
			this.viewTransactionPageLabel.Name = "viewTransactionPageLabel";
			this.viewTransactionPageLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("View Transaction");
			this.actionsNotebook.SetTabLabel (this.viewTransactionWidget, this.viewTransactionPageLabel);
			this.viewTransactionPageLabel.ShowAll ();
			// Container child actionsNotebook.Gtk.Notebook+NotebookChild
			this.phoneCreditWidget = new global::LiqPayDemo.PhoneCreditWidget ();
			this.phoneCreditWidget.Events = ((global::Gdk.EventMask)(256));
			this.phoneCreditWidget.Name = "phoneCreditWidget";
			this.actionsNotebook.Add (this.phoneCreditWidget);
			global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.actionsNotebook[this.phoneCreditWidget]));
			w5.Position = 4;
			// Notebook tab
			this.phoneCreditLabel = new global::Gtk.Label ();
			this.phoneCreditLabel.Name = "phoneCreditLabel";
			this.phoneCreditLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Phone Credit");
			this.actionsNotebook.SetTabLabel (this.phoneCreditWidget, this.phoneCreditLabel);
			this.phoneCreditLabel.ShowAll ();
			// Container child actionsNotebook.Gtk.Notebook+NotebookChild
			this.clicknbuyWidget = new global::LiqPayDemo.ClickNBuyWidget ();
			this.clicknbuyWidget.Events = ((global::Gdk.EventMask)(256));
			this.clicknbuyWidget.Name = "clicknbuyWidget";
			this.actionsNotebook.Add (this.clicknbuyWidget);
			global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.actionsNotebook[this.clicknbuyWidget]));
			w6.Position = 5;
			// Notebook tab
			this.clicknbuyLabel = new global::Gtk.Label ();
			this.clicknbuyLabel.Name = "clicknbuyLabel";
			this.clicknbuyLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Click & Buy");
			this.actionsNotebook.SetTabLabel (this.clicknbuyWidget, this.clicknbuyLabel);
			this.clicknbuyLabel.ShowAll ();
			this.Add (this.actionsNotebook);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 591;
			this.DefaultHeight = 454;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
