
// This file has been generated by the GUI designer. Do not modify.
namespace LiqPayDemo
{
	public partial class ClickNBuyWidget
	{
		private global::Gtk.Table contentTable;

		private global::Gtk.Entry amountEntry;

		private global::Gtk.Label amountLabel;

		private global::Gtk.ComboBoxEntry currencyComboBox;

		private global::Gtk.Label currencyLabel;

		private global::Gtk.Entry defaultPhoneEntry;

		private global::Gtk.Label defaultPhoneLabel;

		private global::Gtk.Entry descriptionEntry;

		private global::Gtk.Label descriptionLabel;

		private global::Gtk.Button generateButton;

		private global::Gtk.Label generatedHtmlLabel;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView generatedHtmlTextView;

		private global::Gtk.Entry merchantIdEntry;

		private global::Gtk.Label merchantIdLabel;

		private global::Gtk.Entry orderIdEntry;

		private global::Gtk.Label orderIdLabel;

		private global::Gtk.ComboBox payWayComboBox;

		private global::Gtk.Label payWayLabel;

		private global::Gtk.Entry pwdEntry;

		private global::Gtk.Label pwdLabel;

		private global::Gtk.Entry resultUrlEntry;

		private global::Gtk.Label resultUrlLabel;

		private global::Gtk.Entry serverUrlEntry;

		private global::Gtk.Label serverUrlLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LiqPayDemo.ClickNBuyWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LiqPayDemo.ClickNBuyWidget";
			// Container child LiqPayDemo.ClickNBuyWidget.Gtk.Container+ContainerChild
			this.contentTable = new global::Gtk.Table (((uint)(12)), ((uint)(2)), false);
			this.contentTable.Name = "contentTable";
			this.contentTable.RowSpacing = ((uint)(6));
			this.contentTable.ColumnSpacing = ((uint)(6));
			// Container child contentTable.Gtk.Table+TableChild
			this.amountEntry = new global::Gtk.Entry ();
			this.amountEntry.CanFocus = true;
			this.amountEntry.Name = "amountEntry";
			this.amountEntry.IsEditable = true;
			this.amountEntry.InvisibleChar = '●';
			this.contentTable.Add (this.amountEntry);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.contentTable[this.amountEntry]));
			w1.TopAttach = ((uint)(5));
			w1.BottomAttach = ((uint)(6));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.amountLabel = new global::Gtk.Label ();
			this.amountLabel.Name = "amountLabel";
			this.amountLabel.Xalign = 1f;
			this.amountLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Amount:");
			this.contentTable.Add (this.amountLabel);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.contentTable[this.amountLabel]));
			w2.TopAttach = ((uint)(5));
			w2.BottomAttach = ((uint)(6));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.currencyComboBox = global::Gtk.ComboBoxEntry.NewText ();
			this.currencyComboBox.Name = "currencyComboBox";
			this.contentTable.Add (this.currencyComboBox);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.contentTable[this.currencyComboBox]));
			w3.TopAttach = ((uint)(6));
			w3.BottomAttach = ((uint)(7));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.currencyLabel = new global::Gtk.Label ();
			this.currencyLabel.Name = "currencyLabel";
			this.currencyLabel.Xalign = 1f;
			this.currencyLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Currency:");
			this.contentTable.Add (this.currencyLabel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.contentTable[this.currencyLabel]));
			w4.TopAttach = ((uint)(6));
			w4.BottomAttach = ((uint)(7));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.defaultPhoneEntry = new global::Gtk.Entry ();
			this.defaultPhoneEntry.CanFocus = true;
			this.defaultPhoneEntry.Name = "defaultPhoneEntry";
			this.defaultPhoneEntry.IsEditable = true;
			this.defaultPhoneEntry.InvisibleChar = '●';
			this.contentTable.Add (this.defaultPhoneEntry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.contentTable[this.defaultPhoneEntry]));
			w5.TopAttach = ((uint)(8));
			w5.BottomAttach = ((uint)(9));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.defaultPhoneLabel = new global::Gtk.Label ();
			this.defaultPhoneLabel.Name = "defaultPhoneLabel";
			this.defaultPhoneLabel.Xalign = 1f;
			this.defaultPhoneLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Default Phone:");
			this.contentTable.Add (this.defaultPhoneLabel);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.contentTable[this.defaultPhoneLabel]));
			w6.TopAttach = ((uint)(8));
			w6.BottomAttach = ((uint)(9));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.descriptionEntry = new global::Gtk.Entry ();
			this.descriptionEntry.CanFocus = true;
			this.descriptionEntry.Name = "descriptionEntry";
			this.descriptionEntry.IsEditable = true;
			this.descriptionEntry.InvisibleChar = '●';
			this.contentTable.Add (this.descriptionEntry);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.contentTable[this.descriptionEntry]));
			w7.TopAttach = ((uint)(7));
			w7.BottomAttach = ((uint)(8));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.descriptionLabel = new global::Gtk.Label ();
			this.descriptionLabel.Name = "descriptionLabel";
			this.descriptionLabel.Xalign = 1f;
			this.descriptionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Description:");
			this.contentTable.Add (this.descriptionLabel);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.contentTable[this.descriptionLabel]));
			w8.TopAttach = ((uint)(7));
			w8.BottomAttach = ((uint)(8));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.generateButton = new global::Gtk.Button ();
			this.generateButton.CanFocus = true;
			this.generateButton.Name = "generateButton";
			this.generateButton.UseUnderline = true;
			this.generateButton.Label = global::Mono.Unix.Catalog.GetString ("Generate");
			this.contentTable.Add (this.generateButton);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.contentTable[this.generateButton]));
			w9.TopAttach = ((uint)(11));
			w9.BottomAttach = ((uint)(12));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.generatedHtmlLabel = new global::Gtk.Label ();
			this.generatedHtmlLabel.Name = "generatedHtmlLabel";
			this.generatedHtmlLabel.Xalign = 1f;
			this.generatedHtmlLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Generated HTML:");
			this.contentTable.Add (this.generatedHtmlLabel);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.contentTable[this.generatedHtmlLabel]));
			w10.TopAttach = ((uint)(10));
			w10.BottomAttach = ((uint)(11));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.generatedHtmlTextView = new global::Gtk.TextView ();
			this.generatedHtmlTextView.CanFocus = true;
			this.generatedHtmlTextView.Name = "generatedHtmlTextView";
			this.generatedHtmlTextView.Editable = false;
			this.GtkScrolledWindow.Add (this.generatedHtmlTextView);
			this.contentTable.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.contentTable[this.GtkScrolledWindow]));
			w12.TopAttach = ((uint)(10));
			w12.BottomAttach = ((uint)(11));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.merchantIdEntry = new global::Gtk.Entry ();
			this.merchantIdEntry.CanFocus = true;
			this.merchantIdEntry.Name = "merchantIdEntry";
			this.merchantIdEntry.IsEditable = true;
			this.merchantIdEntry.InvisibleChar = '●';
			this.contentTable.Add (this.merchantIdEntry);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.contentTable[this.merchantIdEntry]));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.merchantIdLabel = new global::Gtk.Label ();
			this.merchantIdLabel.Name = "merchantIdLabel";
			this.merchantIdLabel.Xalign = 1f;
			this.merchantIdLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Merchant ID:");
			this.contentTable.Add (this.merchantIdLabel);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.contentTable[this.merchantIdLabel]));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.orderIdEntry = new global::Gtk.Entry ();
			this.orderIdEntry.CanFocus = true;
			this.orderIdEntry.Name = "orderIdEntry";
			this.orderIdEntry.IsEditable = true;
			this.orderIdEntry.InvisibleChar = '●';
			this.contentTable.Add (this.orderIdEntry);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.contentTable[this.orderIdEntry]));
			w15.TopAttach = ((uint)(4));
			w15.BottomAttach = ((uint)(5));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.orderIdLabel = new global::Gtk.Label ();
			this.orderIdLabel.Name = "orderIdLabel";
			this.orderIdLabel.Xalign = 1f;
			this.orderIdLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Order ID:");
			this.contentTable.Add (this.orderIdLabel);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.contentTable[this.orderIdLabel]));
			w16.TopAttach = ((uint)(4));
			w16.BottomAttach = ((uint)(5));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.payWayComboBox = global::Gtk.ComboBox.NewText ();
			this.payWayComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("liqpay"));
			this.payWayComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("card"));
			this.payWayComboBox.Name = "payWayComboBox";
			this.payWayComboBox.Active = 0;
			this.contentTable.Add (this.payWayComboBox);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.contentTable[this.payWayComboBox]));
			w17.TopAttach = ((uint)(9));
			w17.BottomAttach = ((uint)(10));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.payWayLabel = new global::Gtk.Label ();
			this.payWayLabel.Name = "payWayLabel";
			this.payWayLabel.Xalign = 1f;
			this.payWayLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Pay Way:");
			this.contentTable.Add (this.payWayLabel);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.contentTable[this.payWayLabel]));
			w18.TopAttach = ((uint)(9));
			w18.BottomAttach = ((uint)(10));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.pwdEntry = new global::Gtk.Entry ();
			this.pwdEntry.CanFocus = true;
			this.pwdEntry.Name = "pwdEntry";
			this.pwdEntry.IsEditable = true;
			this.pwdEntry.InvisibleChar = '●';
			this.contentTable.Add (this.pwdEntry);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.contentTable[this.pwdEntry]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.pwdLabel = new global::Gtk.Label ();
			this.pwdLabel.Name = "pwdLabel";
			this.pwdLabel.Xalign = 1f;
			this.pwdLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
			this.contentTable.Add (this.pwdLabel);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.contentTable[this.pwdLabel]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.resultUrlEntry = new global::Gtk.Entry ();
			this.resultUrlEntry.CanFocus = true;
			this.resultUrlEntry.Name = "resultUrlEntry";
			this.resultUrlEntry.IsEditable = true;
			this.resultUrlEntry.InvisibleChar = '●';
			this.contentTable.Add (this.resultUrlEntry);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.contentTable[this.resultUrlEntry]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.resultUrlLabel = new global::Gtk.Label ();
			this.resultUrlLabel.Name = "resultUrlLabel";
			this.resultUrlLabel.Xalign = 1f;
			this.resultUrlLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Result URL:");
			this.contentTable.Add (this.resultUrlLabel);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.contentTable[this.resultUrlLabel]));
			w22.TopAttach = ((uint)(2));
			w22.BottomAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.serverUrlEntry = new global::Gtk.Entry ();
			this.serverUrlEntry.CanFocus = true;
			this.serverUrlEntry.Name = "serverUrlEntry";
			this.serverUrlEntry.IsEditable = true;
			this.serverUrlEntry.InvisibleChar = '●';
			this.contentTable.Add (this.serverUrlEntry);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.contentTable[this.serverUrlEntry]));
			w23.TopAttach = ((uint)(3));
			w23.BottomAttach = ((uint)(4));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child contentTable.Gtk.Table+TableChild
			this.serverUrlLabel = new global::Gtk.Label ();
			this.serverUrlLabel.Name = "serverUrlLabel";
			this.serverUrlLabel.Xalign = 1f;
			this.serverUrlLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Server URL:");
			this.contentTable.Add (this.serverUrlLabel);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.contentTable[this.serverUrlLabel]));
			w24.TopAttach = ((uint)(3));
			w24.BottomAttach = ((uint)(4));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.contentTable);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.generateButton.Clicked += new global::System.EventHandler (this.OnGenerateHtmlClicked);
		}
	}
}
